Repository StenAfMARS/CDIO4, pull requests merged in 2020-01, with the labels that each got.

#22 Adrian/model fields
  src/main/java/Fields/ModelBrewery.java
  src/main/java/Fields/ModelChanceField.java
  src/main/java/Fields/ModelEstate.java
  src/main/java/Fields/ModelFerry.java
  src/main/java/Fields/ModelField.java
  src/main/java/Fields/ModelGotoJail.java
  src/main/java/Fields/ModelIncomeTax.java
  src/main/java/Fields/ModelParking.java
  src/main/java/Fields/ModelProperty.java
  src/main/java/Fields/ModelStart.java
  src/main/java/Fields/ModelVisitJail.java
  src/main/java/Main.java
Labels: Model

#23 Controller player
  src/main/java/Player/ControllerPlayer.java
  src/main/java/Player/ModelAccount.java
  src/main/java/Player/ModelPlayer.java
Labels: Controller, Model, feature (Must have)

#24 Added ControllerGame
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
  src/main/java/Main.java
  target/classes/Main.class
Labels: Controller, feature (Must have)

#25 Added ControllerField.
  src/main/java/Fields/ControllerField.java
Labels: Controller, feature (Must have)

#26 Silas/controller gui
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
  src/main/java/Player/ControllerPlayer.java
Labels: Controller, feature (Must have)

#28 Display die on game board.
  src/main/java/Game/ControllerGUI.java
Labels: feature (Must have)

#31 Silas/move player
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: Controller, feature (Must have)

#35 Added set owner for a field on GUI
  src/main/java/Game/ControllerGUI.java
Labels: Controller

#36 Silas/controller game
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
  src/main/java/Player/ControllerPlayer.java
Labels: Controller, feature (Must have)

#40 Silas/controller gui
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
Labels: Controller, bug, feature (Must have)

#37 Mathias/chance card controller
  src/main/java/Chancecard/ModelChangeMoneyCard.java
  src/main/java/Chancecard/ModelMoveCard.java
  src/main/java/Chancecard/ModelMoveTo.java
  src/main/java/Chancecard/ModelTaxCard.java
  src/main/java/Game/ControllerGUI.java
Labels: Controller, feature (Must have)

#54 Silas/car color
  .idea/misc.xml
  src/main/java/Game/ControllerGUI.java
Labels: Controller

#58 Silas/car color
  src/main/java/Game/ControllerGUI.java
Labels: bug

#60 Bug fix
  src/main/java/Fields/ControllerField.java
  src/main/java/Game/ControllerGUI.java
Labels: bug

#65 Sejr/language
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: feature (Nice to have)

#68 Silas/bug fix
  src/main/java/Fields/ControllerField.java
  src/main/java/Game/ControllerGUI.java
Labels: bug

#78 Sejr/bug fixes
  src/main/java/Game/ControllerGUI.java
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: bug

#80 Receive money when passing start
  .idea/misc.xml
  src/main/java/Game/ControllerGame.java
  src/main/java/Player/ControllerPlayer.java
Labels: Controller, feature (Must have)

#81 Player can now go to jail
  src/main/java/Player/ControllerPlayer.java
Labels: feature (Nice to have)

#82 Sejr/bug fixes
  src/main/java/Fields/ControllerField.java
  src/main/java/Fields/ModelIncomeTax.java
  src/main/resources/LanguageFiles/Dansk.properties
Labels: bug

#83 Sejr/language
  .idea/misc.xml
  src/main/resources/LanguageFiles/English.properties
Labels: bug

#106 Silas/bug fixes
  src/main/java/Game/ControllerGame.java
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: bug

#110 Adrian/removed unused functions
  src/main/java/Fields/ControllerField.java
  src/main/java/Game/ControllerGUI.java
  src/main/java/Game/ControllerGame.java
  src/main/java/Language/LanguageManager.java
  src/main/java/Player/ControllerPlayer.java
Labels: Refactoring

#111 Silas/bug fix
  .gitignore
  src/main/java/Game/ControllerGame.java
  src/main/java/Game/DiceCarrier.java
  src/main/java/Player/ControllerPlayer.java
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: Refactoring, bug

#114 Silas/bug fix
  .idea/misc.xml
  src/main/java/Fields/ControllerField.java
  src/main/java/Game/ControllerGame.java
  src/main/resources/LanguageFiles/Dansk.properties
  src/main/resources/LanguageFiles/English.properties
Labels: bug
